wiki/web/routes.py
"""
    Routes
    ~~~~~~
"""
import base64
import io
import os

from wiki.core import db
import gridfs
from bson import ObjectId
from flask import Blueprint, Flask, render_template, url_for, send_file, current_app, flash, jsonify
from flask import flash
from flask import redirect
from flask import render_template
from flask import request
from flask import url_for
from flask_login import current_user
from flask_login import login_required
from flask_login import login_user
from flask_login import logout_user
from flask_pymongo import PyMongo

from wiki.core import Processor
from wiki.web.forms import EditorForm
from wiki.web.forms import LoginForm
from wiki.web.forms import RegistrationForm
from wiki.web.forms import SearchForm
from wiki.web.forms import URLForm
from wiki.web import current_wiki
from wiki.web import current_users
from wiki.web.user import protect

bp = Blueprint('wiki', __name__)


@bp.route('/')
@protect
def home():
    page = current_wiki.get('home')
    if page:
        return display('home')
    return render_template('home.html')


@bp.route('/index/')
@protect
def index():
    pages = current_wiki.index()
    return render_template('index.html', pages=pages)


app = Flask(__name__)
app.config["MONGO_URI"] = "mongodb+srv://wiki_user:Zion1997@myriki.vwplv3x.mongodb.net/?retryWrites=true&w=majority"
mongo = PyMongo(app)
ALLOWED_EXTENSIONS = {'txt', 'pdf', 'png', 'jpg', 'jpeg', 'gif'}


@bp.route('/<path:url>/')
@protect
def display(url):
    page = current_wiki.get_or_404(url)

    uploaded_file = None
    if page.file_id:
        gridout = fs.get(page.file_id)
        if gridout.content_type.startswith('image'):

            image_url = url_for('wiki.file', filename=gridout.filename)
            page.body += f'\n<img src="{image_url}" alt="{gridout.filename}">'
        else:

            file_url = url_for('wiki.file', filename=gridout.filename)
            page.body += f'\nDownload file: <a href="{file_url}" download="{gridout.filename}">{gridout.filename}</a>'

    return render_template('page.html', page=page)


from flask import send_file


@bp.route('/image/<identifier>')
def serve_image(identifier):
    fs = gridfs.GridFS(db)

    try:
        _id = ObjectId(identifier)
        grid_out = fs.get(_id)
    except:
        grid_out = fs.get_last_version(filename=identifier)

    response = send_file(grid_out, mimetype=grid_out.content_type)
    return response

@bp.route('/file/<filename>', methods=['GET'])
@protect
def file(filename):
    gridout = fs.get_last_version(filename=filename)
    if gridout:
        return send_file(io.BytesIO(gridout.read()), mimetype=gridout.content_type, as_attachment=True,
                         download_name=filename)
    else:
        flash('File not found', 'error')
        return redirect(url_for('wiki.home'))


@bp.route('/create/', methods=['GET', 'POST'])
@protect
def create():
    form = URLForm()
    if form.validate_on_submit():
        return redirect(url_for(
            'wiki.edit', url=form.clean_url(form.url.data)))
    return render_template('create.html', form=form)


from werkzeug.utils import secure_filename

ALLOWED_EXTENSIONS = {'txt', 'pdf', 'png', 'jpg', 'jpeg', 'gif'}


def allowed_file(filename):
    return '.' in filename and \
        filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS


@bp.route('/edit/<path:url>/', methods=['GET', 'POST'])
@protect
def edit(url):
    session['current_url'] = url
    upload_form = UploadForm()
    page = current_wiki.get(url)
    form = EditorForm(obj=page)

    if form.validate_on_submit():
        if not page:
            page = current_wiki.get_bare(url)

        form.populate_obj(page)
        file = form.file.data

        print("Request files:", request.files)
        print("File:", file)
        print("Form data:", form.data)

        if file and allowed_file(file.filename):
            filename = secure_filename(file.filename)
            file_id = fs.put(file, filename=filename)
            print("File ID:", file_id)

            # Read the uploaded file content
            uploaded_file = fs.get(file_id)
            print("Uploaded file:", uploaded_file)

            uploaded_content = uploaded_file.read().decode('utf-8')


            page.body += '\n' + uploaded_content

            page.file_id = file_id
            page.filepath = url_for('wiki.uploaded_file', filename=filename)


        image_data = form.imageData.data
        if image_data:

            image_data = image_data.split(',', 1)[1]
            image_data = base64.b64decode(image_data)
            image_file = io.BytesIO(image_data)

            image_filename = secure_filename(form.imageName.data)
            image_file_id = fs.put(image_file, filename=image_filename)

            image_url = url_for('wiki.file', filename=image_filename)
            page.body += f'\n<img src="{image_url}" alt="{image_filename}">'

        page.save()
        flash('"%s" was saved.' % page.title, 'success')
        return redirect(url_for('wiki.display', url=url))

    return render_template('editor.html', upload_form=upload_form, form=form, page=page)


from wiki.core import fs
from wiki.web.forms import UploadForm
from flask import session


@bp.route('/upload/', methods=['POST'])
@protect
def upload():
    if 'file' in request.files:
        file = request.files['file']
        if file and allowed_file(file.filename):
            filename = secure_filename(file.filename)
            file_id = fs.put(file, filename=filename)
            session['file_id'] = str(file_id)
            flash('File was uploaded.', 'success')

            # Return the file ID and filename in the response
            return jsonify({'file_id': str(file_id), 'filename': filename})

    return redirect(url_for('wiki.edit', url=session.get('current_url', '')))

@bp.route('/preview/', methods=['POST'])
@protect
def preview():
    data = {}
    processor = Processor(request.form['body'])
    data['html'], data['body'], data['meta'] = processor.process()
    return data['html']


@bp.route('/move/<path:url>/', methods=['GET', 'POST'])
@protect
def move(url):
    page = current_wiki.get_or_404(url)
    form = URLForm(obj=page)
    if form.validate_on_submit():
        newurl = form.url.data
        current_wiki.move(url, newurl)
        return redirect(url_for('wiki.display', url=newurl))
    return render_template('move.html', form=form, page=page)


@bp.route('/delete/<path:url>/')
@protect
def delete(url):
    page = current_wiki.get_or_404(url)
    current_wiki.delete(url)
    flash('Page "%s" was deleted.' % page.title, 'success')
    return redirect(url_for('wiki.home'))


@bp.route('/tags/')
@protect
def tags():
    tags = current_wiki.get_tags()
    return render_template('tags.html', tags=tags)


@bp.route('/tag/<string:name>/')
@protect
def tag(name):
    tagged = current_wiki.index_by_tag(name)
    return render_template('tag.html', pages=tagged, tag=name)


@bp.route('/search/', methods=['GET', 'POST'])
@protect
def search():
    form = SearchForm()
    if form.validate_on_submit():
        results = current_wiki.search(form.term.data, form.ignore_case.data)
        return render_template('search.html', form=form,
                               results=results, search=form.term.data)
    return render_template('search.html', form=form, search=None)


@bp.route('/user/login/', methods=['GET', 'POST'])
def user_login():
    form = LoginForm()
    if form.validate_on_submit():
        user = current_users.get_user(form.name.data)
        login_user(user)
        user.set('authenticated', True)
        flash('Login successful.', 'success')
        return redirect(request.args.get("next") or url_for('wiki.index'))
    return render_template('login.html', form=form)


from flask import render_template, flash, redirect, url_for
from flask_login import login_required
from wiki.web.forms import ChangePasswordForm
from wiki.web import current_users

@bp.route('/changepass/', methods=['GET', 'POST'])
@login_required
def change_password():
    form = ChangePasswordForm()

    if form.validate_on_submit():
        # Assuming current_users is an instance of UserManager
        user_manager = current_users

        # Retrieve the current user
        current_user = user_manager.get_user(form.name.data)

        # Check the current password
        if current_user.check_password(form.password.data):
            # Change the password using UserManager methods
            new_password = form.new_password.data
            current_user.data['authentication_method'] = 'cleartext'
            current_user.data['password'] = new_password
            current_user.save()

            flash('Password changed successfully.', 'success')
            return redirect(url_for('wiki.index'))
        else:
            flash('Current password is incorrect.', 'danger')

    return render_template('changepass.html', form=form)


@bp.route('/register/', methods=['GET', 'POST'])
def user_register():
    form = RegistrationForm()
    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data

        # Using current_users directly, assuming it's a UserManager instance
        user = current_users.add_user(username, password)

        if user:
            login_user(user)
            user.set('authenticated', True)
            flash('Registration and login successful.', 'success')
            return redirect(request.args.get("next") or url_for('wiki.index'))
        else:
            flash('Username already exists. Please choose a different one.', 'danger')

    return render_template('register.html', form=form)



@bp.route('/user/logout/')
@login_required
def user_logout():
    current_user.set('authenticated', False)
    logout_user()
    flash('Logout successful.', 'success')
    return redirect(url_for('wiki.index'))


@bp.route('/user/')
def user_index():
    pass


@bp.route('/user/create/')
def user_create():
    pass

wiki/web/templates/base.html
{% from "helpers.html" import input %}
<!DOCTYPE html>
<html>
	<head>
		<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='bootstrap.css') }}">
		<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='responsive.css') }}">
		<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='pygments.css') }}">
	</head>

	<body>
		<div class="navbar navbar-fixed-top">
			<div class="navbar-inner">
				<div class="container">
					<div class="row">
						<div class="span12">
							<a href="#" class="brand">{{ config.TITLE }}</a>
							<ul class="nav">
								<li><a href="{{ url_for('wiki.home') }}">Home</a></li>
								<li><a href="{{ url_for('wiki.index') }}">Index</a></li>
								<li><a href="{{ url_for('wiki.tags') }}">Tags</a></li>
								<li><a href="{{ url_for('wiki.search') }}">Search</a></li>
								<li class="divider-vertical"></li>
								<li><a href="{{ url_for('wiki.create') }}">New Page</a></li>
								<li class="divider-vertical"></li>
								<li></li>
							</ul>

							<ul class="nav pull-right">
								<li><a href="{{ url_for('wiki.change_password')}}">Change Password</a></li>
								<li class="divider-vertical"></li>
								{% if current_user.is_anonymous %}

									<li><a href="{{ url_for('wiki.user_register')}}">Register</a></li>
									<li><a href="{{ url_for('wiki.user_login') }}">Login</a></li>
								{% else %}
									<li><a href="{{ url_for('wiki.user_logout') }}">Logout</a></li>
								{% endif %}
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>

		<div class="container">
			<div class="row">
				<div class="span10 offset1">
					{% block header %}
						<div class="page-header">
							<h1>{% block title %}{{ page.title }}{% endblock title %}</h1>
						</div>
					{% endblock header %}
				</div>
			</div>
			<div class="row">
				<div class="span7 offset1">
					{% with messages = get_flashed_messages(with_categories=True) %}
						{% if messages %}
							{% for category, message in messages %}
								<div class="alert alert-{{ category }}">
									<button type="button" class="close" data-dismiss="alert">&times;</button>
									{{ message }}
								</div>
							{% endfor %}
						{% endif %}
					{% endwith %}
					{% if form and form.errors %}
						<div class="alert alert-error">Errors occured verifying your input. Please check the marked fields below.</div>
					{% endif %}
					{% block content %}
					{% endblock content %}
				</div>
				<div class="span3">
					{% block sidebar %}
					{% endblock sidebar %}
				</div>
			</div>
		</div>
		<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jquery/1.9.0/jquery.min.js "></script>
		<script type="text/javascript">
			if (typeof jQuery == 'undefined') {
				document.write(unescape("%3Cscript src='{{ url_for('static', filename='jquery.min.js') }}' type='text/javascript'%3E%3C/script%3E"));
			}
		</script>
		<script src="{{ url_for('static', filename='bootstrap.min.js') }}"></script>
		<script type="text/javascript">
			{% block postscripts %}
			{% endblock postscripts %}
		</script>
	</body>
</html>

wiki/web/templates/changepass.html
{% extends "base.html" %}

{% block title %}Change Password{% endblock title %}

{% block content %}
<form method="post" class="form-inline">
    {{ form.hidden_tag() }}
    {{ form.name(placeholder='Username', class='form-control') }}
    {{ form.password(placeholder='Current Password', class='form-control') }}
    {{ form.new_password(placeholder='New Password', class='form-control') }}
    <div class="mb-2"></div>
    <input type="submit" class="btn btn-primary mt-2" value="Submit">
</form>
{% endblock content %}

wiki/web/templates/create.html
{% extends "base.html" %}

{% block title %}Create a new page{% endblock title %}
{% block content %}
<form method="POST" class="form-inline">
	{{ form.hidden_tag() }}
	{{ input(form.url, placeholder="URL of the new page", autocomplete="off") }}
	<input type="submit" class="btn btn-success" value="Create">
</form>
{% endblock content %}

{% block sidebar %}
<p class="alert alert-success">Thank you for creating new content!</p>
{% endblock sidebar %}

wiki/web/templates/editor.html
{% extends "base.html" %}

{% block title -%}
Wiki Editor
{%- endblock title %}

{% block content %}
<ul class="nav nav-tabs">
    <li class="active"><a href="#editor" data-toggle="tab">Editor</a></li>
    <li><a href="#preview" data-toggle="tab" id="previewlink">Preview</a></li>
</ul>

<div class="tab-content">
    <div class="tab-pane active" id="editor">
        <!-- Image Upload Form -->
        <form action="{{ url_for('wiki.upload') }}" method="post" enctype="multipart/form-data">
            {{ upload_form.hidden_tag() }}
            <div class="form-group">
                <label for="file">Choose File:</label>
                {{ upload_form.file() }}
            </div>
            <button type="submit" class="btn btn-primary">Upload</button>
        </form>

        <!-- Editor Form -->
        <form method="post" class="form">
            {{ form.hidden_tag() }}
            {{ input(form.title, placeholder="Title", class="span7", autocomplete="off") }}
            {{ input(form.body, placeholder="Markdown", class="span7", rows="20") }}
            {{ input(form.tags, placeholder="Tags (comma separated)", class="span7", autocomplete="off") }}

            <!-- Display uploaded images -->
            <div id="uploaded-content">
            {% for image_id in images %}
             <img src="{{ url_for('wiki.display_image', image_id=image_id) }}" alt="Image">
                {% endfor %}
            </div>
            <div class="form-actions">
                <div class="pull-left">
                    <a class="btn" href="#preview" id="previewbtn">Preview</a>
                </div>
                <div class="pull-right">
                    <a class="btn" href="{{ url_for('wiki.display', url=page.url) }}">Cancel</a>
                    <button class="btn btn-success" type="submit">Save</button>
                </div>
            </div>
        </form>
    </div>

    <div class="tab-pane" id="preview"></div>
</div>
{% endblock content %}

wiki/web/templates/helpers.html
{% macro input(field) -%}
	<div class="control-group {% if field.errors %}error{% endif %}">
		{% if field.type == 'BooleanField' %}
			<div class="controls">
				<label for="{{ field.name }}" class="checkbox">
					{{ field(**kwargs) }}
					{{ field.label.text }}
				</label>
			</div>
		{% else %}
			<label for="{{ field.name }}" class="control-label">{{ field.label.text }}</label>
			<div class="controls">
				{{ field(**kwargs) }}
				{% if field.errors %}
					<div>
						{% for error in field.errors %}
							<span class="help-inline">
								{{ error }}
							</span>
						{% endfor %}
					</div>
				{% endif %}
			</div>
		{% endif %}
	</div>
{%- endmacro %}

wiki/web/templates/home.html
{% extends "base.html" %}
{% block title -%}
    Welcome to your new wiki!
{% endblock title %}

{% block content %}
<p>You did not create any content yet. Your wiki recommends you, to do so now, as every user will see this page first, and you would want to make a good impression, wouldn't you?</p>
<p><a href="{{ url_for('wiki.edit', url='home') }}" class="btn btn-success">Create a homepage</a></p>
{% endblock %}

wiki/web/templates/index.html
{% extends "base.html" %}

{% block title %}Page Index{% endblock title %}

{% block content %}
{% if pages %}
	<table class="table">
		<thead>
			<tr>
				<th>Title</th>
				<th>URL</th>
			</tr>
		</thead>
		<tbody>
			{% for page in pages %}
				<tr>
					<td><a href="{{ url_for('wiki.display', url=page.url) }}">{{ page.title }}</a></td>
					<td><a href="{{ url_for('wiki.display', url=page.url) }}">{{ page.url }}</a></td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
{% else %}
	<p>There are no pages yet.</p>
{% endif %}
{% endblock content %}

{% block sidebar %}
<ul class="nav nav-tabs nav-stacked">
	<li><a href="{{ url_for('wiki.create') }}">New Page</a></li>
	<li><a href="{{ url_for('wiki.tags') }}">Tag List</a></li>
	<li><a href="{{ url_for('wiki.search') }}">Search</a></li>
</ul>
{% endblock sidebar %}

wiki/web/templates/login.html
{% extends "base.html" %}

{% block title %}Login{% endblock title %}

{% block content %}
<form class="form form-inline" method="POST">
	{{ form.hidden_tag() }}
	{{ form.name(placeholder='Username') }}
	{{ form.password(placeholder='Password') }}
	<input type="submit" class="btn btn-primary" value="Login">
</form>
{% endblock content %}

wiki/web/templates/move.html
{% extends "base.html" %}

{% block title %}Move a page{% endblock title %}
{% block content %}
<form method="POST" class="form-inline">
    {{ form.hidden_tag() }}
    {{ input(form.url, placeholder="New URL of the page", autocomplete="off") }}
    <input type="submit" class="btn btn-success" value="Create">
</form>
{% endblock content %}

{% block sidebar %}
<p class="alert alert-success">Be careful, the old url will be invalid immediately!</p>
{% endblock sidebar %}

wiki/web/templates/page.html
{% extends "base.html" %}

{% block title %}
    {{ page.title }}
{% endblock title %}

{% block content %}
    <div id="confirmDelete" class="modal hide fade" aria-hidden="true">
        <div class="modal-header">
            <h3>Are you sure?</h3>
        </div>
        <div class="modal-body">
            <p>Are you sure you want to delete {{ page.title }}?  This cannot be undone.</p>
        </div>
        <div class="modal-footer">
            <a href="#" class="btn" data-dismiss="modal" aria-hidden="true">No</a>
            <a href="{{ url_for('wiki.delete', url=page.url) }}" class="btn btn-danger">Yes, delete.</a>
        </div>
    </div>
    {{ page }}

    <!-- Display uploaded images -->
    <div id="uploaded-content">
        {% for image in images %}
            <img src="{{ url_for('wiki.display_image', image_id=image) }}" alt="Image">
        {% endfor %}
    </div>d
{% endblock content %}

{% block sidebar %}
    {% if page.tags %}
        <h3>Tags</h3>
        <ul>
            {% for tag in page.tags.split(',') %}
                <li><a href="{{ url_for('wiki.tag', name=tag.strip()) }}">{{ tag|trim }}</a></li>
            {% endfor %}
        </ul>
    {% endif %}
    <h3>Actions</h3>
    <ul class="nav nav-tabs nav-stacked">
        <li><a href="{{ url_for('wiki.edit', url=page.url) }}">Edit</a></li>
        <li><a href="{{ url_for('wiki.move', url=page.url) }}">Move</a></li>
        <li><a href="#confirmDelete" data-toggle="modal" class="text-error">Delete</a></li>
    </ul>
{% endblock sidebar %}

wiki/web/templates/register.html
{% extends "base.html" %}

{% block title %}Register{% endblock title %}

{% block content %}
<form method="post" class="form-inline">
    {{ form.hidden_tag() }}
    {{ form.username(placeholder='Username', class='form-control') }}
    {{ form.password(placeholder='Password', class='form-control') }}
    {{ form.confirm_password(placeholder='Confirm Password', class='form-control') }}
    <input type="submit" class="btn btn-primary" value="Register">
</form>
{% endblock content %}

wiki/web/templates/search.html
{% extends "base.html" %}

{% block title %}
{% if search %}
	Results for "{{ search }}"
{% else %}
	Search
{% endif %}
{% endblock title %}

{% block content %}
<div class="row">
	<div class="span8 offset1">
		<form class="form-inline well" method="POST">
			{{ form.hidden_tag() }}
			{{ form.term(placeholder='Search for.. (regex accepted)', autocomplete="off") }}
            {{ form.ignore_case() }} Ignore Case
			<input type="submit" class="btn btn-success pull-right" value="Search!">
		</form>
	</div>
</div>

{% if search %}
	{% if results %}
		<ul>
			{% for result in results %}
				<li><a href="{{ url_for('wiki.display', url=result.url) }}">{{ result.title }}</a></li>
			{% endfor %}
		</ul>
	{% else %}
		<p>No results for your search.</p>
	{% endif %}
{% endif %}
{% endblock content %}

wiki/web/templates/tag.html
{% extends "base.html" %}

{% block title %}Pages tagged {{ tag }}{% endblock title %}

{% block content %}
{% if pages %}
	<table class="table">
		<thead>
			<tr>
				<th>Title</th>
				<th>URL</th>
			</tr>
		</thead>
		<tbody>
			{% for page in pages %}
				<tr>
					<td><a href="{{ url_for('wiki.display', url=page.url) }}">{{ page.title }}</a></td>
					<td><a href="{{ url_for('wiki.display', url=page.url) }}">{{ page.url }}</a></td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
{% else %}
	<p>There are no pages tagged {{ tag }}.</p>
{% endif %}
{% endblock content %}

wiki/web/templates/tags.html
{% extends "base.html" %}

{% block title %}Index by Tags{% endblock title %}

{% block content %}
{% if tags %}
	<table class="table">
		<thead>
			<tr>
				<th>Tag</th>
				<th>Number of Articles</th>
			</tr>
		</thead>
		<tbody>
			{% for tag, pages in tags|dictsort %}
				<tr>
					<td><a href="{{ url_for('wiki.tag', name=tag) }}">{{ tag }}</a></td>
					<td>{{ pages|length }}</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
{% else %}
	<p>There are no tags in use so far.</p>
{% endif %}
{% endblock content %}